deployment:
  imageURL: 169189304039.dkr.ecr.us-east-1.amazonaws.com/roboshop/user
  imageVersion: IMAGE_VERSION
hpa:
  maxReplicas: 10
  utilisation: 75 

  configMap:
  MONGO_URL: mongodb://mongodb:27017/catalogue